baseURL = 'https://mattpopa.github.io/'
languageCode = 'en-us'
title = 'CloudCat'
theme = "ananke"
resourceDir = "../resources"


[params]
text_color = ""
author = "Matt Popa"
favicon = ""
site_logo = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/matei-popa-ro/"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/mattpopa"
