baseURL = 'https://cloudcat.digital/'
languageCode = 'en-us'
title = 'CloudCat'
theme = "PaperMod"
resourceDir = "../resources"

[params]
author = "Matt Popa"
colorMode = "light"
favicon = "images/logo_no_test.jpeg"
site_logo = "images/logo_small.jpg"

# Social media links
socials = [
    { name = "GitHub", url = "https://github.com/mattpopa", icon = "github" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/matei-popa-ro/", icon = "linkedin" }
]
