baseURL = 'https://cloudcat.digital/'
languageCode = 'en-us'
title = 'CloudCat Digital'
theme = "PaperMod"
resourceDir = "../resources"

[params]
author = "Matt Popa"
colorMode = "light"
favicon = "images/logo_no_test.jpeg"
site_logo = "images/logo_small.jpg"
description = "Bringing big-league cloud expertise to businesses of all sizes. We're a specialized cloud and DevOps agency with a deep focus on AWS, Kubernetes, and CI/CD, offering over a decade of experience in crafting streamlined, secure, and scalable cloud solutions. Our mission is to simplify the cloud, making advanced technology accessible and effective for every business."

[params.social]
GitHub = "https://github.com/mattpopa"
LinkedIn = "https://www.linkedin.com/in/matei-popa-devops/"

