baseURL = 'https://cloudcat.digital/'
languageCode = 'en-us'
title = 'CloudCat Digital'
theme = "PaperMod"
resourceDir = "../resources"

[params]
author = "Matt Popa"
colorMode = "light"
description = "Bringing big-league cloud expertise to businesses of all sizes. We specialize in AWS, Kubernetes, and CI/CD pipelines, crafting streamlined, secure, and scalable solutions."
showDescriptionInHeader = true

[params.images]
favicon = "images/favicon.ico"
opengraph = "images/logo_no_text.jpeg"

[params.logo]
logo = "images/logo_small.jpg"
logoText = "CloudCat Digital"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 30

[params.social]
GitHub = "https://github.com/mattpopa"
LinkedIn = "https://www.linkedin.com/in/matei-popa-devops/"
